language: r
cache: packages
env:
  - MAKEFLAGS = -j2 ODBCSYSINI=${TRAVIS_BUILD_DIR}/travis/odbc INCLUDE_DIR=/usr/include LIB_DIR=/usr/lib/x86_64-linux-gnu/

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - unixodbc unixodbc-dev
      - odbc-postgresql
      - libmyodbc
      - libsqliteodbc

before_install: |
  mkdir ~/.R
  cat <<EOF > ~/.R/Makevars
  CXX1X=g++-5
  CXX1XSTD=-std=c++11

before_script:
  - sudo -u postgres psql -U postgres -c 'CREATE DATABASE test_db;'
  - sudo -u postgres psql -U postgres -c "ALTER USER postgres WITH PASSWORD 'password';"
  - mysql -u root -e 'CREATE DATABASE test_db;'

after_success:
  - R -e 'options(covr.gcov = "/usr/bin/gcov-4.9");covr::codecov()'
