language: r
cache: packages
env:
  - MAKEFLAGS = -j2

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libiodbc2
      - iodbc
      - libiodbc2-dev
      - gcc-4.9
      - g++-4.9

before_install: |
  mkdir ~/.R
  cat <<EOF > ~/.R/Makevars
  CXX1X=g++-4.9
  CXX1XSTD=-std=c++11

before_script:
  - sudo -u postgres psql -U postgres -c 'CREATE DATABASE test_db;'
  - sudo -u postgres psql -U postgres -c "ALTER USER postgres WITH PASSWORD 'password';"
  - export ODBCSYSINI=${PWD}/travis/odbc
