sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - g++-5
      - libboost-locale1.55-dev
      - libboost-test1.55-dev
      - libsqliteodbc
      - unixodbc

language: cpp

compiler:
  - gcc

env:
    - USE_UNICODE=OFF USE_BOOST_CONVERT=OFF
    - USE_UNICODE=OFF USE_BOOST_CONVERT=ON
    - USE_UNICODE=ON  USE_BOOST_CONVERT=OFF
    - USE_UNICODE=ON  USE_BOOST_CONVERT=ON

install:
  - cat /etc/odbc.ini
  - echo "[sqlite]" > /etc/odbc.ini
  - echo "Description=SQLite3 ODBC Driver" >> /etc/odbc.ini
  - echo "Driver=/usr/lib/odbc/libsqlite3odbc.so" >> /etc/odbc.ini
  - echo "Setup=/usr/lib/odbc/libsqlite3odbc.so" >> /etc/odbc.ini
  - echo "Threading=2" >> /etc/odbc.ini
  - cat /etc/odbc.ini

before_script:
  - if [[ "$CXX" == "g++" ]]; then export CXX="g++-5"; fi
  - mkdir build
  - cd build

script:
  - cmake -D NANODBC_USE_UNICODE=${USE_UNICODE} -D NANODBC_USE_BOOST_CONVERT=${USE_BOOST_CONVERT} -D NANODBC_ENABLE_LIBCXX=NO ..
  - make VERBOSE=1 sqlite_check
