language: r
cache: packages
dist: trusty
env:
  - MAKEFLAGS = -j2 ODBCSYSINI=${TRAVIS_BUILD_DIR}/travis/odbc INCLUDE_DIR=/usr/include LIB_DIR=/usr/lib/x86_64-linux-gnu/

r:
  - oldrel
  - release
  - devel

warnings_are_errors: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - unixodbc-dev
      - odbc-postgresql
      - libmyodbc
      - libsqliteodbc

before_script:
  - sudo -u postgres psql -U postgres -c 'CREATE DATABASE test_db;'
  - sudo -u postgres psql -U postgres -c "ALTER USER postgres WITH PASSWORD 'password';"
  - mysql -u root -e 'CREATE DATABASE test_db;'

r_github_packages:
  - rstats-db/DBItest@9087f76

after_success:
  - R -e 'covr::codecov(line_exclusions = c("src/nanodbc.h", "src/nanodbc.cpp"))'
