language: r
cache: packages
env:
  - MAKEFLAGS = -j2 ODBCSYSINI=${TRAVIS_BUILD_DIR}/travis/odbc INCLUDE_DIR=/usr/include LIB_DIR=/usr/lib/x86_64-linux-gnu/

r:
  - oldrel
  - release
  - devel

warnings_are_errors: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - unixodbc unixodbc-dev
      - odbc-postgresql
      - libmyodbc
      - libsqliteodbc

before_install: |
  mkdir ~/.R
  cat <<EOF > ~/.R/Makevars
  CXX1X=g++-4.9
  CXX1XSTD=-std=c++11
  CXX1XPICFLAGS=-fPIC

before_script:
  - sudo -u postgres psql -U postgres -c 'CREATE DATABASE test_db;'
  - sudo -u postgres psql -U postgres -c "ALTER USER postgres WITH PASSWORD 'password';"
  - mysql -u root -e 'CREATE DATABASE test_db;'

after_success:
  - R -e 'options(covr.gcov = "/usr/bin/gcov-4.9");covr::codecov(line_exclusions = c("src/nanodbc.h", "src/nanodbc.cpp"))'
